### ISSUE TITLE
Example code does not compile

### ISSUE THREAD

**Issue by Behrouz-m** [ThanosFisherman/MayI#1]
`Mayi.withActivity(this)
            .withPermissions(Manifest.permission.READ_CONTACTS, Manifest.permission.ACCESS_FINE_LOCATION)
            .onRationale(this::permissionRationaleMulti)
            .onResult(this::permissionResultMulti)
            .check()`

**Comment by ThanosFisherman** [comment]
Hello,

I don't have any problems compiling the sample app. Do you get any error messages?

**Comment by ThanosFisherman** [comment]
Closing this for now. Feel free to reopen it and post a stacktrace of the error.
