### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [ThanosFisherman/MayI#1]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by ThanosFisherman** [comment]
Hello @mansya 

Thanks for reaching out. That sounds like a great idea. Feel free to contribute with an icon/logo. Let me know if you need any help with the concept of the library in order to design something relevant.

**Comment by mansya** [comment]
hi sir. I have design logo for this project. what do you think ? do you like it ? which one do you like ? let me know if there is someone who wants to change.

**Comment by mansya** [comment]
hi sir. I have designed the logo for this project. do you like it ? if yes which one do you like?
![mayl](https://user-images.githubusercontent.com/33461607/45169033-eaa54080-b226-11e8-9798-95af0283976e.png)
let me know if there is a change!

**Comment by mansya** [comment]
I have upload all files to this [**Drive**](https://drive.google.com/open?id=18_2mxiLJEmm-FXHVIFKx6HwBwPRSWF8O). And I have sent you [**Pull Requests**](https://github.com/ThanosFisherman/MayI/pull/2). Please check it.

**Comment by ThanosFisherman** [comment]
Thank you very much for your contribution. Everything seems in order. I will be proceeding on a merge soon.

I might also need some new icons for my future commercial projects (not open source) so I will keep you in my mind and let you know. You will be paid of course. :)

Thanks

**Comment by mansya** [comment]
Of course. I will wait for your good news.
